import os
from typing import List

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, status
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
import traceback

from src.api.schemas import ChatRequest, ChatResponse
from src.api.gemini_client import generate_reply

# Load environment variables from .env at startup
load_dotenv()

# Environment variables
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-1.5-flash")
# Prefer explicit dev origins by default to avoid wildcard + credentials pitfalls
ALLOWED_ORIGINS_RAW = os.getenv(
    "ALLOWED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000"
)

# Build allowed origins list from CSV value
allowed_origins: List[str] = [
    o.strip() for o in (ALLOWED_ORIGINS_RAW or "").split(",") if o.strip()
]

# Create FastAPI app with metadata and tags for OpenAPI
app = FastAPI(
    title="AI Copilot Backend",
    description=(
        "FastAPI backend that exposes chat and health endpoints, "
        "integrating with Google's Gemini API to generate assistant replies."
    ),
    version="1.0.0",
    openapi_tags=[
        {"name": "health", "description": "Service health and readiness checks."},
        {
            "name": "chat",
            "description": "Chat endpoint to interact with the Gemini AI assistant.",
        },
    ],
)

@app.on_event("startup")
async def _on_startup():
    # Helpful diagnostic logging; prints to uvicorn logs on boot
    print(
        "[AI Copilot Backend] Startup complete. Expected to be served by uvicorn on 0.0.0.0:3001. "
        f"Allowed origins: {allowed_origins or '[]'}. "
        f"Model: {GEMINI_MODEL or 'unset'}. "
        f"API key configured: {'yes' if (GEMINI_API_KEY and GEMINI_API_KEY.strip()) else 'no'}"
    )

# Configure CORS using ALLOWED_ORIGINS
app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# PUBLIC_INTERFACE
@app.get(
    "/",
    tags=["health"],
    summary="Service Index",
    description="Basic info and readiness links for the AI Copilot Backend.",
    responses={200: {"description": "Service info"}},
)
def index():
    """Index route to quickly verify the backend is reachable."""
    try:
        print("[AI Copilot Backend] GET / - served index")
    except Exception:
        # Avoid raising due to logging errors
        pass
    return JSONResponse(
        {
            "service": "AI Copilot Backend",
            "status": "running",
            "docs": "/docs",
            "health": "/health",
            "chat": "/chat",
        }
    )


# PUBLIC_INTERFACE
@app.get(
    "/health",
    tags=["health"],
    summary="Health Check",
    description="Returns a simple status indicating the service is up.",
    responses={
        200: {
            "description": "Service is healthy",
            "content": {"application/json": {}},
        }
    },
)
def health_check():
    """Health check endpoint."""
    try:
        print("[AI Copilot Backend] GET /health - ok")
    except Exception:
        pass
    return {"status": "ok"}


# PUBLIC_INTERFACE
@app.post(
    "/chat",
    tags=["chat"],
    summary="Chat with Gemini",
    description=(
        "Accepts a user message with optional prior history and returns the AI assistant reply "
        "generated by Gemini. Requires the GEMINI_API_KEY environment variable."
    ),
    response_model=ChatResponse,
    responses={
        200: {"description": "Successful Response"},
        400: {"description": "Invalid request or configuration"},
        500: {"description": "Unexpected server error"},
    },
)
async def chat(request: ChatRequest) -> ChatResponse:
    """Handle chat requests by sending the message and optional history to Gemini."""
    # Log minimal request context for troubleshooting
    try:
        hist_len = len(request.history or [])
        print(f"[AI Copilot Backend] POST /chat - message length={len(request.message or '')}, history={hist_len}, model={GEMINI_MODEL}")
    except Exception:
        pass

    # Validate configuration
    if not GEMINI_API_KEY or not GEMINI_API_KEY.strip():
        print("[AI Copilot Backend] /chat error - GEMINI_API_KEY missing")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Server not configured: GEMINI_API_KEY is missing.",
        )

    try:
        reply_text = await generate_reply(
            message=request.message,
            history=request.history or [],
            api_key=GEMINI_API_KEY,
            model=GEMINI_MODEL,
        )
        return ChatResponse(reply=reply_text)
    except ValueError as ve:
        # Input or parsing related errors
        print(f"[AI Copilot Backend] /chat ValueError: {ve}")
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(ve)) from ve
    except Exception as exc:
        # Unexpected errors
        print("[AI Copilot Backend] /chat unexpected error:\n" + "".join(traceback.format_exc()))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to generate reply from Gemini.",
        ) from exc

# PUBLIC_INTERFACE
@app.post(
    "/api/chat",
    tags=["chat"],
    summary="Chat with Gemini (alias)",
    description="Alias endpoint for /chat to avoid path prefix mismatches.",
    response_model=ChatResponse,
    responses={
        200: {"description": "Successful Response"},
        400: {"description": "Invalid request or configuration"},
        500: {"description": "Unexpected server error"},
    },
)
async def chat_alias(request: ChatRequest) -> ChatResponse:
    """Alias endpoint that forwards to /chat handler."""
    return await chat(request)
